# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadDataFiles.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 350)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.filePathLE = QtWidgets.QLineEdit(self.groupBox)
        self.filePathLE.setObjectName("filePathLE")
        self.gridLayout.addWidget(self.filePathLE, 0, 1, 1, 2)
        self.openFilePB = QtWidgets.QToolButton(self.groupBox)
        self.openFilePB.setObjectName("openFilePB")
        self.gridLayout.addWidget(self.openFilePB, 0, 3, 1, 1)
        self.loadFilePB = QtWidgets.QPushButton(self.groupBox)
        self.loadFilePB.setMinimumSize(QtCore.QSize(0, 40))
        self.loadFilePB.setObjectName("loadFilePB")
        self.gridLayout.addWidget(self.loadFilePB, 2, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.datetimeFormatLE = QtWidgets.QLineEdit(self.groupBox)
        self.datetimeFormatLE.setObjectName("datetimeFormatLE")
        self.gridLayout.addWidget(self.datetimeFormatLE, 1, 1, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "数据导入模块"))
        self.groupBox.setTitle(_translate("Form", "正在导入一个新的数据"))
        self.openFilePB.setText(_translate("Form", "..."))
        self.loadFilePB.setText(_translate("Form", "导入数据"))
        self.label.setText(_translate("Form", "选择一个数据文件夹地址："))
        self.label_3.setText(_translate("Form", "数据采用时间："))
